# Experiment 6a: Multi-task learning — age regression ONLY
# MTL — age regression only

multitask: true
lambda_age: 0.2
lambda_centre: 0.0

loss: "ce"
use_class_weights: false
sampler: "weighted"
ensemble: false